### ISSUE TITLE
showing error while running the code "harmonic.py"

### ISSUE THREAD

**Issue by paulamimajumder** [daniloefl/hfpython#1]
![screenshot from 2018-11-18 21-15-05](https://user-images.githubusercontent.com/45146551/48674859-102fbe00-eb77-11e8-99c1-baef31078205.png)

**Comment by daniloefl** [comment]
Hi,
sorry that I didn't see this before, but it seems like you are trying to copy and paste the code in a Jupyter notebook, while still reading the argv input. The code was made to be run in command line, so that you can type:

```
python harmonic.py 1
```

The argument 1 is sent to `sys.argv` and it specifies the energy level to look for. You can replace it with 0 to look for the ground state energy level or any other positive integer.

I propose you try running it in a command line. If you want to run it in a Jupyter Notebook, then you will have to adapt the code (ie: instead of reading the target energy level from `sys.argv`, just set it to a fixed number).

Best regards,
Danilo
